import { SessionProvider } from '@/providers/SessionProvider'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '../../css/globals.css'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={montserrat.className}>{children}</body>
      </html>
    </SessionProvider>
  )
}
